name: AI Code Audit

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.py'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Run Audit
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          git fetch origin main
          for file in $(git diff --name-only origin/main...HEAD | grep '.py$'); do
            echo "📄 Auditing: $file"
            python code_audit.py "$file"
          done
